# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewUrlo < Formula
  desc "A simple CLI tool to open URLs from the command line"
  homepage "https://github.com/ryo034/homebrew-urlo"
  version "1.0.15"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.15/homebrew-urlo_Darwin_arm64.tar.gz"
      sha256 "3a6aa726693b0dd40698e22bef677e970f208cf6575224b450992c1d32dbce89"

      def install
        bin.install "urlo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.15/homebrew-urlo_Darwin_x86_64.tar.gz"
      sha256 "4de4ec1a355d494c7c70b5b68e02fb9a1fe6d7f053baaf60486608f095009e8b"

      def install
        bin.install "urlo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.15/homebrew-urlo_Linux_x86_64.tar.gz"
      sha256 "6839eaa2d94f4298c239a49788e6a584b0542b7b0756f5884eae188027b34ce7"

      def install
        bin.install "urlo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.15/homebrew-urlo_Linux_arm64.tar.gz"
      sha256 "dfa4cd6046f66435710f3bbeed4be7d44577138994599d34c3f8564996736e8c"

      def install
        bin.install "urlo"
      end
    end
  end

  test do
    urlo --version
  end
end
