# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewUrlo < Formula
  desc "A simple CLI tool to open URLs from the command line"
  homepage "https://github.com/ryo034/homebrew-urlo"
  version "1.0.26"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.26/homebrew-urlo_Darwin_x86_64.tar.gz"
      sha256 "a78842b918090e89740c3ad4be278300c8e92b550d94878c605fd7a27ca7cf73"

      def install
        bin.install "urlo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.26/homebrew-urlo_Darwin_arm64.tar.gz"
      sha256 "7a8f8888903670d48c1958fdb7faf72dba7ef601b6a0491570739abfe277c470"

      def install
        bin.install "urlo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.26/homebrew-urlo_Linux_x86_64.tar.gz"
      sha256 "16433ee9afef979bb083eb0b4c312d78482cc404624d55d01b9c6d22afbce8a6"

      def install
        bin.install "urlo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryo034/homebrew-urlo/releases/download/v1.0.26/homebrew-urlo_Linux_arm64.tar.gz"
      sha256 "cce122a68281b026684c3b06c142603b43168e774634b45343e10b971913c788"

      def install
        bin.install "urlo"
      end
    end
  end

  test do
    urlo --version
  end
end
