# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Urlo < Formula
  desc "A simple CLI tool to open URLs from the command line"
  homepage "https://github.com/ryo034/homebrew-urlo"
  version "1.0.5"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryo034/urlo/releases/download/v1.0.5/urlo_Darwin_x86_64.tar.gz"
      sha256 "be181861e849e37216189f8ea430dfa5d51e2d06883c2f86d51ae8afb464e93a"

      def install
        bin.install "urlo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryo034/urlo/releases/download/v1.0.5/urlo_Darwin_arm64.tar.gz"
      sha256 "c38992188a638626f8fa93f3269a4d13730f81ea84bcc4fda10d9ff72d68aa5f"

      def install
        bin.install "urlo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryo034/urlo/releases/download/v1.0.5/urlo_Linux_x86_64.tar.gz"
      sha256 "158832779fadfe2ec9b0a1286a205b16192eb5fe8338f348f9a77883b4cf907c"

      def install
        bin.install "urlo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryo034/urlo/releases/download/v1.0.5/urlo_Linux_arm64.tar.gz"
      sha256 "bf3c0dd2b23ec0bf177e26e9a65f94302de4f9989f568b579879705e8749c402"

      def install
        bin.install "urlo"
      end
    end
  end

  test do
    urlo --version
  end
end
